# publish-resume sends the updated resume to GH Pages
name: publish-resume

# Run only when something gets merged to the default branch
on:
  push:
    branches:
      - main
      - feature/gha

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Check out the code itself
      - name: Checkout
        uses: actions/checkout@v2

      # Install pdf->png tool first before even trying to compile PDF
      - name: Install pdftoppm 
        run: sudo apt-get update && sudo apt-get install -y poppler-utils texlive latexmk

      # # Build latex source into a PDF
      # - name: Compile PDF
      #   uses: xu-cheng/latex-action@v2
      #   with:
      #     root_file: resume.tex
      #     args: '-pdf -file-line-error -halt-on-error -interaction=nonstopmode -output-directory=build'
      #     post_compile: 'latexmk -c -output-directory=build'
 
      - name: Compile PDF manually
        run: |
          latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -output-directory=build

      # Double check that we produced a valid PDF
      - name: Validate
        run: |
          file ./build/resume.pdf | grep -q ' PDF '

      - name: debug PDF
        run: |
          echo "ls build"
          ls build
          echo "file build/resume.pdf"
          file build/resume.pdf
          echo "cat build/resume.pdf"
          cat build/resume.pdf

      # Convert each page of the PDF into a separate image
      - name: Generate Preview Images
        run: |
          cd build 
          pdftocairo -r 600 resume.pdf resume-preview -png

      - name: check image output
        run: |
          echo "ls ."
          ls .
          echo "ls build"
          ls build

      - name: check pdftoppm version
        run: pdftoppm -v

      # Commit the generated resources to the gh-pages branch, which
      # is automatically synced to the GH Pages site at 
      # bclarkx2.github.io/resume
      - name: Upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build
          # exclude_assets: '.github,**.aux,**.fdb_latexmk,**.fls,**.log,**.out'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

