# release-resume throws the updated resume onto a release on GH
name: release-resume

# Only run when a tag is created
on: 
  push:
    tags:
      - "v.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Check out the code itself
      - name: Checkout
        uses: actions/checkout@v2
      
      # Build latex source into a PDF
      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          args: '-pdf -file-line-error -halt-on-error -interaction=nonstopmode -output-directory=build'
      
      # Double check that we produced a valid PDF
      - name: Validate
        run: |
          file ./build/resume.pdf | grep -q ' PDF '
      
      # Clean generated files
      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          args: '-output-directory=build -c'
      
      # Release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/resume.pdf

